program: main.o kolejka.o lista.o stos.o
	g++ main.o kolejka.o stos.o lista.o -o program
main.o: main.cpp
	g++ main.cpp -c
kolejka.o: kolejka.cpp kolejka.hh
	g++ kolejka.cpp -c
lista.o: lista.cpp lista.hh
	g++ lista.cpp -c
stos.o: stos.cpp stos.hh
	g++ stos.cpp -c
